name: level2
comment: comment

algorithm:
  name: multinav2
  repository: https://github.com/cipollone/multinav2/
  version: 0.2.1
  commit: null
  diff: null
  params:
    resume_file: null
    initialize_file: null
    active_passive_agents: false
    action_bias: null
    action_bias_eps: 0.0
    learning_rate: 0.1
    learning_rate_end: 0.01
    total_timesteps: 100000
    q_eps: 0.95
    epsilon_end: 0.0
    log_interval: 500
    gamma: 1.0

environment:
  name: gym-sapientino
  repository: https://github.com/whitemech/gym-sapientino.git
  version: multinav-experiments
  commit: f2d44472d3d3d9ec2431f7cd3e4a949b165a1446
  diff: ''
  params:
    env: level2
    episode_time_limit: 30
    render: false
    nb_rooms: 1
    sapientino_fail_p: 0.05
    shaping: null
    rewards:
      - ldlf: "<(!out0)*>(<out0>tt & (<closed>end | (<!closed>tt & <true; (!in0)*>(<in0>tt & (<person; interact>end | <!person; !interact>end)))))"
        reward: 1.0
evaluation:
  episodes: 0
  frequency: 0
n-runs: 1
output-base: outputs
run-command: "poetry run python -m multinav train"
