name: level1
comment: grid sapientino office environment

algorithm:
  name: multinav2
  repository: https://github.com/cipollone/multinav2/
  version: 0.2.1
  commit: null
  diff: null
  params:
    resume_file: null
    initialize_file: null
    active_passive_agents: false  # TODO: activate
    action_bias: null
    action_bias_eps: 0.0
    learning_rate: 0.1
    learning_rate_end: 0.01
    gamma: 1.0
    total_timesteps: 700000
    q_eps: 0.99
    epsilon_end: 0.0
    log_interval: 500

environment:
  name: gym-sapientino
  repository: https://github.com/whitemech/gym-sapientino.git
  version: develop
  commit: ''
  diff: ''
  params:
    env: level1
    initial_position: [2, 3]
    shaping: null  # TODO: shaping off
    episode_time_limit: 70
    render: false
    reward_per_step: 0.0
    reward_outside_grid: 0.0
    reward_duplicate_beep: 0.0
    nb_rooms: 3
    rewards:
      - dfa: ./outputs/level2/0/logs/dfa-0.pickle
        reward: 1.0
    map: |-
      | B ##############|
      |##b##############|
      |## ##############|
      |                 |
      |                 |
      |             r   |
      |##g########## ###|
      |## ##########y###|
      |##p########## ###|
evaluation:
  episodes: 0
  frequency: 0
n-runs: 1
output-base: outputs
run-command: "poetry run python -m multinav train"
