name: rooms1-shinv
comment: "Reach a specific location in the map: gridworld"

algorithm:
  name: multinav2
  repository: https://github.com/cipollone/multinav2/
  version: 0.2.1
  commit: null
  diff: null
  params:
    resume_file: null
    initialize_file: null
    active_passive_agents: true
    action_bias: null
    action_bias_eps: 0.0
    exploration_policy: null
    learning_rate: 0.05
    learning_rate_end: 0.01
    gamma: 0.98
    total_timesteps: 300000
    q_eps: 0.8
    epsilon_end: 0.0
    log_interval: 1000

environment:
  name: gym-sapientino
  repository: https://github.com/whitemech/gym-sapientino.git
  version: develop
  commit: ''
  diff: ''
  params:
    env: rooms1
    reward_shift: 0.0
    initial_position: [3, 12]
    shaping: ./outputs/rooms2/0/models/model_100000.pickle
    shaping_gamma: 0.98
    return_invariant: true
    episode_time_limit: 100
    fail_p: 0.05
    render: false
    reward_per_step: 0.0
    reward_outside_grid: 0.0
    reward_duplicate_beep: 0.0
    rewards:
      - dfa: ./outputs/rooms2/0/logs/dfa-0.pickle
        reward: 1.0
    rooms_connectivity:
      - [g, p]
      - [g, b]
      - [y, p]
      - [y, B]
      - [o, B]
      - [o, r]
      - [o, b]
      - [r, b]
    map: |-
      |###############|
      |#ggg#ppp#ppyyy#|
      |#ggg#p#p#p#yyy#|
      |#ggg#p#p#p#yyy#|
      |#ggggp#ppp#yyy#|
      |###bb######BBB#|
      |#bbbbbbbbb#BBB#|
      |#bbbbbbbbb#BBB#|
      |#bbbbbbbbbbooo#|
      |#bbbbbbbbbbooo#|
      |#bbbbbbbbbbooo#|
      |#bbbbbbbbbbrrr#|
      |#bbbbbbbbbbrrr#|
      |#bbbbbbbbb#rrr#|
      |###############|
evaluation:
  episodes: 0
  frequency: 0
n-runs: 10
output-base: outputs
run-command: "poetry run python -m multinav train"
