name: rooms1-sh
comment: "Reach a specific location in the map: gridworld"

algorithm:
  name: multinav2
  repository: https://github.com/cipollone/multinav2/
  version: 0.2.1
  commit: null
  diff: null
  params:
    resume_file: null
    initialize_file: null
    active_passive_agents: true
    action_bias: null
    action_bias_eps: 0.0
    exploration_policy: null
    learning_rate: 0.1
    learning_rate_end: 0.05
    gamma: 0.99
    total_timesteps: 500000
    q_eps: 0.8
    epsilon_end: 0.0
    log_interval: 1000

environment:
  name: gym-sapientino
  repository: https://github.com/whitemech/gym-sapientino.git
  version: develop
  commit: ''
  diff: ''
  params:
    env: rooms1
    reward_shift: -1.0
    initial_position: [2, 3]
    shaping: ./outputs/rooms2/0/models/model_100000.pickle
    shaping_gamma: 0.99
    return_invariant: false
    episode_time_limit: 130
    render: false
    reward_per_step: 0.0
    reward_outside_grid: 0.0
    reward_duplicate_beep: 0.0
    rewards:
      - dfa: ./outputs/rooms2/0/logs/dfa-0.pickle
        reward: 1.0
    rooms_connectivity:
      - [g, b]
      - [g, r]
      - [r, y]
      - [y, p]
      - [p, o]
      - [p, B]
      - [B, G]
    map: |-
      |###########################################|
      |#ggggggg#bbbbbbbb##########oooooooooooo####|
      |#ggggggggbbbbbbbb#pppppppppoooooooooooo####|
      |#ggggggg#bbbbbbbb#pppppppp#oooooooooooo####|
      |#ggggggg#bbbbbbbb#pppppppp#oooooooooooo####|
      |###r##############pppppppp#o###############|
      |#rrrrrrr#yyyyyyyy#pppppppp#BBBBBBBBBBBB#GG#|
      |#rrrrrrrryyyyyyyy#ppppppppBBBBBBBBBBBBBBGG#|
      |#rrrrrrr#yyyyyyyyypppppppp#BBBBBBBBBBBB####|
      |#rrrrrrr#yyyyyyyy##########BBBBBBBBBBBB####|
      |###########################################|
evaluation:
  episodes: 0
  frequency: 0
n-runs: 10
output-base: outputs
run-command: "poetry run python -m multinav train"
