name: rooms8-1sh-1error
comment: "8 rooms, gridworld, q-learning and our shaping, 1 model mistake"

algorithm:
  name: multinav2
  repository: https://github.com/cipollone/multinav2/
  version: 0.2.5
  commit: null
  diff: null
  params:
    resume_file: null
    initialize_file: null
    active_passive_agents: true
    algorithm: Q
    action_bias: null
    action_bias_eps: 0.0
    exploration_policy: null
    learning_rate: 0.02
    learning_rate_end: 0.002
    gamma: 0.98
    total_timesteps: 500000
    q_eps: 0.9
    epsilon_end: 0.1
    log_interval: 500
    rollout_interval: 2000
    rollout_episodes: 10

environment:
  name: gym-sapientino
  repository: https://github.com/whitemech/gym-sapientino.git
  version: develop
  commit: ''
  diff: ''
  params:
    env: rooms1
    reward_shift: 0.0
    initial_position: [2, 3]
    shaping: "./outputs/rooms8-2-1error/0/models/model_50000.pickle"
    shaping_gamma: 0.98
    return_invariant: false
    episode_time_limit: 100
    fail_p: 0.05
    render: false
    reward_per_step: 0.0
    reward_outside_grid: 0.0
    reward_duplicate_beep: 0.0
    rewards:
      - dfa: "./outputs/rooms8-2/0/logs/dfa-0.pickle"
        reward: 1.0
    fluents: rooms
    rooms_connectivity:
      - [g, b]
      - [g, r]
      - [r, y]
      - [y, p]
      - [p, o]
      - [o, B]
      - [p, B]
      - [p, G]
      - [B, G]
    map: |-
      |#########################|
      |#gggg#bbbb######ooooo####|
      |#gggggbbbb#pppppooooo####|
      |#gggg#bbbb#pppp#ooooo####|
      |#gggg#bbbb#pppp#ooooo####|
      |###r#######pppp#o########|
      |#rrrr#yyyy#pppp#BBBBB#GG#|
      |#rrrrryyyy#ppppBBBBBBBGG#|
      |#rrrr#yyyyypppp#BBBBB####|
      |#rrrr#yyyy######BBBBB####|
      |#########################|
evaluation:
  episodes: 0
  frequency: 0
n-runs: 10
output-base: outputs
run-command: "poetry run python -m multinav train"
