name: rooms1
comment: "Reach a specific location in the map: gridworld"

algorithm:
  name: multinav2
  repository: https://github.com/cipollone/multinav2/
  version: 0.2.1
  commit: null
  diff: null
  params:
    resume_file: null
    initialize_file: null
    active_passive_agents: true
    action_bias: null
    action_bias_eps: 0.0
    learning_rate: 0.05
    learning_rate_end: 0.01
    gamma: 0.98
    total_timesteps: 400000
    q_eps: 0.9
    epsilon_end: 0.05
    log_interval: 500

environment:
  name: gym-sapientino
  repository: https://github.com/whitemech/gym-sapientino.git
  version: develop
  commit: ''
  diff: ''
  params:
    env: rooms1
    initial_position: [2, 3]
    shaping: null
    shaping_gamma: null
    episode_time_limit: 200
    render: false
    reward_per_step: 0.0
    reward_outside_grid: 0.0
    reward_duplicate_beep: 0.0
    rewards:
      - dfa: ./outputs/level2/0/logs/dfa-0.pickle
        reward: 1.0
    map: |-
      |#########################|
      |#gggg#bbbb######ooooo####|
      |#gggggbbbb#pppppooooo####|
      |#gggg#bbbb#pppp#ooooo####|
      |#gggg#bbbb#pppp#ooooo####|
      |###r#######pppp#o########|
      |#rrrr#yyyy#pppp#BBBBB#GG#|
      |#rrrrryyyy#ppppBBBBBBBGG#|
      |#rrrr#yyyyypppp#BBBBB####|
      |#rrrr#yyyy######BBBBB####|
      |#########################|
evaluation:
  episodes: 0
  frequency: 0
n-runs: 10
output-base: outputs
run-command: "poetry run python -m multinav train"
